### ISSUE TITLE
bool hints create invalid json

### ISSUE THREAD

**Issue by whihathac** [baldator/Poshstache#15] opened 2020-03-29 18:56 UTC
Template:
```
"Account_enabled": {
      "value": {{#AccountEnabled}}{{AccountEnabled}}{{/AccountEnabled}}{{^AccountEnabled}}false{{/AccountEnabled}}
}
```

Hint:
```
{
  "AccountEnabled": true
}
```
Output:
```
"Account_enabled": {
      "value": True
}
```

I think it has to do with Powershell's $true/$false ToString conversion leads to True/False instead of true/false

**Comment by whihathac** [comment] 2020-03-30 06:12
Seems like both ConvertFrom-JsonToHashtable and ConvertFrom-Json change the bool into True/False respectively in $JSonInput itself. So even before we go to Stubble, inputs messed up.

Basically, have been able to repro this issue in both PS 5.x and PS Core 7

**Comment by baldator** [comment] 2020-04-01 20:54
As you mentioned the problem is related to the $true/$false ToString conversion. 
I've implemented a flag to force the script to consider each field as a string instead of bool, however, I consider it more a "hack" than a feature... I'm still thinking if it'd be a good idea to add it to the upstream.
I've committed the change to bugfix/#15 branch. Would you like to test it and let me know if it fixes your issue?

**Comment by whihathac** [comment] 2020-04-06 17:01
Sorry I missed this message, I'll check this in a bit.

**Comment by whihathac** [comment] 2020-04-07 06:06
Seems to be working, will you close this issue when you publish new version?

**Comment by whihathac** [comment] 2020-04-07 06:06
And thanks a bunch for quick fixes!

**Comment by baldator** [comment] 2020-04-08 21:33
new version published

**Closed as completed by baldator** 2020-04-08 21:33 UTC

**Comment by puya-ms** [comment] 2023-05-17 04:49
Not sure why but I still see this happening in both 0.1.9 and 0.1.10.

**Comment by puya-ms** [comment] 2023-05-17 04:49
@baldator Not sure why but I still see this happening in both 0.1.9 and 0.1.10.
